resources:
  repositories:
    - repository: templates
      type: github
      name: kmadof/devops-templates
      endpoint: kmadof

steps:
- template: templates/template.yaml@templates
  parameters:
    repo: templates