variables:
  fullRepoName: 'kmadof/devops-templates'
  repoName: $(basename $(fullRepoName))

resources:
  repositories:
    - repository: devops
      type: github
      name: $(fullRepoName)
      endpoint: kmadof

steps:
- checkout: self
- checkout: devops
- script: |
    echo $(Build.SourcesDirectory)
    ls $(Build.SourcesDirectory) *
- template: templates/template.yaml@devops
  parameters:
    repo: $(repoName)