resources:
  repositories:
    - repository: templates
      type: github
      name: kmadof/devops-templates
      endpoint: kmadof

steps:
- script: |
    echo $(Build.SourcesDirectory)
    ls $(Build.SourcesDirectory) -a
- template: templates/template.yaml@templates
  parameters:
    repo: templates