# https://stackoverflow.com/questions/63941345/set-variable-group-dynamically-using-system-pullrequest-targetbranch

variables:
  test: $(System.PullRequest.TargetBranch)

jobs:
- job: myJob
  timeoutInMinutes: 10
  variables:
  - ${{ if contains(variables['System.PullRequest.TargetBranch'], 'master') }}:
    - group: PROD
  - ${{ if contains(variables['System.PullRequest.SourceBranch'], 'test') }}:
    - group: PROD
  - ${{ if contains(variables['test'], 'master') }}:
    - group: PROD
  # - ${{ if contains(variables['build.sourceBranch'], 'refs/pull/24/merge')}}: # it works with this
  #   - group: PROD
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      echo '$(test)'
      echo 'System.PullRequest.TargetBranch - $(System.PullRequest.TargetBranch)'
      echo 'System.PullRequest.SourceBranch - $(System.PullRequest.SourceBranch)'
      echo 'build.sourceBranch- $(build.sourceBranch)'
  - script: echo My favorite vegetable is $(name).
