# https://stackoverflow.com/questions/63941345/set-variable-group-dynamically-using-system-pullrequest-targetbranch

jobs:
- job: myJob
  timeoutInMinutes: 10
  variables:
  - ${{ if contains(variables['System.PullRequest.TargetBranch'], 'master') }}:
    - group: PROD
  - ${{ if contains(variables['build.sourceBranch'], 'refs/heads/test')}}:
    - group: PROD
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo '$(System.PullRequest.TargetBranch)'
  - script: echo '$(build.sourceBranch)'
  - script: echo My favorite vegetable is ${{ variables.name }}.
