stages:
- stage:
  displayName: 'Build and Restore'
  variables:
  - name: isProd
    value: true
  - ${{ if eq(variables['isProd'], 'false') }}:
    - group: QA
  - ${{ if eq(variables['isProd'], 'true') }}:
    - group: PROD
  - jobs:
    - job:
      steps:
      - script: echo $(name) # uses macro syntax
      - script: echo $[variables.name] # uses runtime expression
