stages:
- stage:
  displayName: 'Build and Restore'
  variables:
  - name: isProd
    value: true
  - template: qa.yaml
  jobs:
    - job:
      steps:
      - script: echo $(name) # uses macro syntax | run time expression doesn't work for templates $[variables.name] 
