parameters:
- name: environment
  displayName: Environment
  type: string
  default: QA
  values:
  - QA
  - PROD

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - variable-groups-01/*

stages:
- stage:
  displayName: 'Build and Restore'
  variables:
  - group: ${{ parameters.environment }}
  jobs:
    - job:
      steps:
      - script: echo $(isProd)
      - script: echo $(name) # uses macro syntax | run time expression doesn't work for templates $[variables.name] 
