stages:
- stage:
  displayName: 'Build and Restore'
  variables:
  - group:
    ${{ if eq(variables['isProd'], false) }}: QA
    ${{ if eq(variables['isProd'], true) }}: PROD
  jobs:
    - job:
      steps:
      - script: echo $(isProd)
      - script: echo $(name) # uses macro syntax | run time expression doesn't work for templates $[variables.name] 
