stages:
- stage:
  displayName: 'Build and Restore'
  variables:
  - name: isProd
    value: true
  - template: qa.yml
  jobs:
    - job:
      steps:
      - script: echo $(name) # uses macro syntax
      - script: echo $[variables.name] # uses runtime expression
