stages:
- stage:
  displayName: 'Build and Restore'
  variables:
  - name: isProd
    value: true
  ${{ if eq(variables['isProd'], 'false') }}:
  - template: qa.yaml
  ${{ if eq(variables['isProd'], 'true') }}:
  - template: prod.yaml
  jobs:
    - job:
      steps:
      - script: echo $(name) # uses macro syntax | run time expression doesn't work for templates $[variables.name] 
