# https://stackoverflow.com/questions/67603812/how-can-i-prompt-for-variables-when-launching-azure-devops-pipelines

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: versionName
  value: ''

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
