trigger: none

strategy:
  matrix:
    a_server:
      service: a-server
      path: somepath
      imageName: ubuntu-latest
    b_server:
      service: b-server
      path: somepath
      imageName: ubuntu-latest
  maxParallel: 2

pool:
  vmImage: $(imageName)

steps:
- script: | 
    echo '$(path)'
    echo '$(service)'
