parameters:
- name: Multiline
  type: object

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    echo <<< EOL
    ${{ parameters.Multiline }}
    EOL >> script.txt
    cat script.txt
