# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: environment
  displayName: 'Environment'
  default: 'QA Server'
  type: string
  values: 
  - 'QA Server'
  - 'DEV Server'
  - 'PROD Server'
  
trigger: none

variables:
- name: QA
  value: 'SERVER_0562'
- name: DEV
  value: 'SERVER_5149'
- name: PROD
  value: 'SERVER_1892'

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: 'windows-latest'
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.environment }}
  - powershell: |
      if($x -eq 10){
        write-host("Value of X is 10")
      } elseif($x -eq 20){
        write-host("Value of X is 20")
      } elseif($x -eq 30){
        write-host("Value of X is 30")
      } else {
        write-host("This is else statement")
      }
  - powershell: |
      If('${{ parameters.environment }}' -eq '$(QA)') {
        Write-Host '##vso[task.setvariable variable=folderName;isOutput=true]$(QA)'
      } ElseIf('${{ parameters.environment }}' -eq '$(DEV)') {
        Write-Host '##vso[task.setvariable variable=folderName;isOutput=true]$(DEV)'
      } ElseIf('${{ parameters.environment }}' -eq '$(PROD)') {
        Write-Host '##vso[task.setvariable variable=folderName;isOutput=true]$(PROD)'
      }
  - powershell: |
      Write-Host $(folderName)
      
