# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: Ubuntu
  values:
  - windows-latest
  - Ubuntu
  - macOS-latest
  
trigger: none

jobs:
- job: build
  displayName: build
  pool: 
    ${{ if eq(variables['Build.SourceBranchName'], 'Ubuntu') }}:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.image }}