# https://stackoverflow.com/questions/65739111/running-azure-pipeline-tasks-inside-a-docker

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-18.04'

container: ubuntu:18.04

steps:
- bash: |
    apt-get update && apt-get install -y lsb-release && apt-get clean all
    lsb_release -a
