# https://stackoverflow.com/questions/64642449/conditions-based-on-resources-on-yaml-pipeline/64643767?noredirect=1#comment114556002_64643767
trigger: none
pr: none

resources:
  repositories:
    - repository: devops
      type: github
      name: kmadof/devops-templates
      endpoint: kmadof

variables:
  tools.ref: $[ resources.repositories['devops'].ref ]
  isMain: $[eq(resources.repositories['devops'].ref, 'refs/heads/master')]

steps:
- checkout: self
- checkout: devops
- script: |
    echo $(Build.SourcesDirectory)
    ls $(Build.SourcesDirectory) *
- template: templates/template.yaml@devops
  parameters:
    repo: devops-templates
- bash: |
    echo 'Tools version: $TOOLS_REF'
- script: |
    echo 'test with condition'
  condition: and(succeeded(), eq(variables.isMain, true))