# https://stackoverflow.com/questions/63678236/link-azure-devops-ci-and-cd-yaml-pipelines

trigger:
  branches:
    include:
      - master

resources:
  pipelines:
  - pipeline: test
    source: kmadof.dm-so-46
    trigger:
      branches:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo '$(Build.TriggeredBy.BuildNumber)'!
  displayName: 'Run a one-line script'

- script: |
    echo '$(Build.TriggeredBy.BuildNumber)'!
    echo '$(Build.TriggeredBy.BuildId)'!
    echo '$(Build.TriggeredBy.DefinitionId)'!
    echo '$(Build.TriggeredBy.DefinitionName)'!
    echo '$(Build.TriggeredBy.ProjectID)'!
    echo '$(Build.BuildNumber)'!
    echo '$(Build.RequestedFor)'!
    echo '$(Build.RequestedForEmail)'!
    echo '$(Build.RequestedForId)'!
  displayName: 'Run a multi-line script'
