trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo "##vso[task.setvariable variable=packages]{"name":"John","age":30,"cars":[ "Ford", "BMW", "Fiat" ]}"
  displayName: 'Set variable'

- script: |
    echo "$(packages)"
  displayName: 'Display variable'