trigger: none
name: ColorOutput

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    ##[group]Beginning of a group
    ##[warning]Warning message
    ##[error]Error message
    ##[section]Start of a section
    ##[debug]Debug text
    ##[command]Command-line being run
    ##[endgroup]
  displayName: 'Run a multi-line script'
