# https://stackoverflow.com/questions/63678236/link-azure-devops-ci-and-cd-yaml-pipelines

trigger:
  branches:
    include:
      - master

resources:
  pipelines:
  - pipeline: test
    source: kmadof.dm-so-46
    trigger:
      branches:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo '$(Build.TriggeredBy.BuildNumber)'!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
