# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  old_date: '20210601'
  latest_date: '20210603'
  PSI: ${{ variables.latest_date - variables.old_date}}
  # PSI: ${{ (variables.latest_date-variables.old_date)/56+1}}
  # totalsprints: ${{ (variables.latest_date-variables.old_date)/14 }}
  # sprint: ${{ variables.totalsprints%4+1 }}
  majorversion: '2.'
  dot: '.'

#name: '$(majorversion)$(Year:yy)$(PSI)$(dot)$(sprint)$(dot)$(Date:MMdd)'
name: '$(majorversion)$(Year:yy)$(PSI)$(dot)$(Date:MMdd)'

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
