trigger:
- master

resources:
- repo: self

variables:
  vmImageName: 'windows-latest'
  AppName: 'MyApplication'

stages:
- stage: Build
  displayName: Build stage
  jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            ls -la
      - task: SqlAzureDacpacDeployment@1
        inputs:
          azureSubscription: 'rg-the-code-manual'
          AuthenticationType: 'server'
          ServerName: 'kmad'
          DatabaseName: 'tcm'
          SqlUsername: 'kmad'
          SqlPassword: '2fDo0xD36An0'
          deployType: 'InlineSqlTask'
          SqlInline: |
            CREATE USER [$(AppName)] FROM EXTERNAL PROVIDER;
            ALTER ROLE db_datareader ADD MEMBER [$(AppName)];
            ALTER ROLE db_datawriter ADD MEMBER [$(AppName)];
            GO
          InlineAdditionalArguments: '-v $(ApiAppName)'
          IpDetectionMethod: 'AutoDetect'
          
- stage: Deploy
  displayName: Deploy Notebook Instance Stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: CmdLine@2
              inputs:
                script: echo Some debug text!