# https://stackoverflow.com/questions/64340688/nuget-push-to-artifacts-from-build-script-fails-to-authenticate

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- pwsh: |
    export PATH=$PATH:$HOME/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
    dotnet tool install fake-cli -g
- pwsh: |

    fake run build.fsx -e token=$env:MYSECRET
  workingDirectory: $(Build.SourcesDirectory)/stackoverflow/72-fake-nuegt-publish
  env:
    MySecret: $(System.AccessToken)