# https://stackoverflow.com/questions/64607815/yaml-pipeline-execute-task-if-resources-triggeringalias-ui

parameters:
- name: compileui
  displayName: compile ui
  type: boolean
  default: false

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: hadar   # Name of the pipeline resource
    source: kmadof.hadar # Name of the pipeline referenced by the pipeline resource
    trigger: 
      branches:
      - releases/*
      - master

steps:
- script: |
    echo $(Build.Reason)
    echo $(Build.TriggeredBy.BuildId)
    echo $(Build.TriggeredBy.DefinitionId)
    echo $(Build.TriggeredBy.DefinitionName)
    echo $(Build.TriggeredBy.BuildNumber)