trigger:
  branches:
    include:
    - master
    - refs/tags/*
  paths:
    include:
    - stackoverflow/29-pipeline-artifacts/*

# no PR triggers
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: A
  jobs:
  - job: JA
    steps:
    - pwsh: |
        $content = 'Awesome artifact'
        New-Item -Path $(Build.ArtifactStagingDirectory) -Name "testsummary.md" -ItemType "file" -Value $content
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: someArtifact
      

#stage B runs if DetermineResult task set doThing variable n stage A
- stage: B
  dependsOn: A
  jobs:
  - job: JB
    steps:
    - download: current
      artifact: someArtifact
    - bash: echo "Deployment to production"