trigger: none
pr: none

pool:
  vmImage: windows-latest

steps:
- pwsh: |
    cd stackoverflow/84-powershell
    ls
    .\s1.ps1 "$(Build.SourcesDirectory)\stackoverflow\84-powershell\s2.ps1"