trigger:
  branches:
    include:
    - master
  paths:
    include:
    - stackoverflow/38-endpoint-replace/*
    exclude:
    - '*'

# no PR triggers
pr: none

pool:
  vmImage: 'ubuntu-latest'

#https://stackoverflow.com/questions/62044055/is-it-possible-to-cancel-a-azure-devops-pipeline-job-programmatically

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "I'm here"
      if ('$(SomeVariable' -eq 'Stop') {
        exit 0
      }
      Write-Host "And now here"
    name: ConditionalStep
    pwsh: true
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     condition: in(task.ConditionalStep.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
#     script: |
#       Write-Host "Am I here?""
#     pwsh: true