trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath' # Optional. Options: filePath, inline
    filePath: 'test.ps1'
    workingDirectory:  $(Build.SourcesDirectory)/stackoverflow/77-powershell