pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    pwsh: true
    targetType: inline
    script: ls $(Agent.HomeDirectory)\bin
- task: PowerShell@2
  condition: succeeded()
  displayName: "Create a list"
  inputs:
    targetType: 'inline'
    script: |

      $myList = New-Object System.Collections.ArrayList

      $myList.Add("wow")

      Write-Output ("##vso[task.setvariable variable=MyList;]$myList")

- template: myRandomListTaskTemplate2.yml
  parameters:
    MyList: 
    - item1
    - item2
