# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - gated-checkin-angular-app/*
    exclude:
    - gated-checkin-angular-app/azure-pipelines-gc.yml

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:

- template: build-and-test.yaml

- script: echo Some steps to create artifacts!
  displayName: 'Run a one-line script'
