# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Test
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    varOS: $(Agent.OS)
  steps:
    - pwsh: |
        echo $env:TestVar
        echo $env:OS
        echo $env:IsMaster
        printenv
      env:
        OS: $(varOS)
        ${{ if eq(variables['varOS'], 'Windows_NT') }}:
          TestVar: "I am Windows"
        ${{ if eq(variables['varOS'], 'Linux') }}:
          TestVar: "I am Linux"
        ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master')}}:
          IsMaster: "true"
