
trigger:
  branches:
    include:
    - '*'
    exclude:
    - master
  paths:
    include:
    - docker-multiple-apps/*
    exclude:
    - docker-multiple-apps/*.ymal


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: devopsmanual-acr

- task: Docker@2
  displayName: Build and Push
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: docker-multiple-apps/DOCKERFILE
    tags: |
      build-on-agent

- task: Docker@2
  displayName: Logout of ACR
  inputs:
    command: logout
    containerRegistry: devopsmanual-acr