
trigger:
  branches:
    include:
    - '*'
    exclude:
    - master
  paths:
    include:
    - docker-multiple-apps/*
    exclude:
    - docker-multiple-apps/*.ymal

# no PR triggers
pr: none

pool:
  vmImage: 'ubuntu-latest'
  gitRepoName: $(Build.Repository.Name)
  imgRepoName: ${{ basename variables['gitRepoName'])}}

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: devopsmanual-acr

- task: Docker@2
  displayName: Build and Push
  inputs:
    repository: $(imgRepoName)
    command: build
    Dockerfile: docker-multiple-apps/Dockerfile
    tags: |
      build-on-agent

- task: Docker@2
  displayName: Logout of ACR
  inputs:
    command: logout
    containerRegistry: devopsmanual-acr