trigger:
  branches:
    include:
      - master
  paths:
    include:
      - stackoverflow/06/*

#https://stackoverflow.com/questions/61306564/azure-devops-build-pipeline-doesnt-build-executables

pool:
 vmImage: 'ubuntu-latest'


steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'stackoverflow/06/SimpleApp.csproj'
    argumnets: '-c Release -o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- bash: ls $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'