trigger:
- master

pool:
 vmImage: 'ubuntu-latest'


steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '*.csproj'
    argumnets: '-c Release -o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    workingDirectory: stackoverflow/06

- bash: ls $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifact@1
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'