trigger:
  branches:
    include:
      - master
  paths:
    include:
      - stackoverflow/06/*

# no PR triggers
pr: none

#https://stackoverflow.com/questions/61306564/azure-devops-build-pipeline-doesnt-build-executables

pool:
 vmImage: 'windows-latest'


steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'stackoverflow/06/SimpleApp.csproj'

- pwsh: ls $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'