trigger:
  branches:
    include:
    - master
    - refs/tags/*
  paths:
    include:
    - stackoverflow/28-tags/*
# https://stackoverflow.com/questions/61783014/using-lerna-js-and-azure-devops-pipeline/61786014?noredirect=1#comment109330301_61786014
# git tag release-05
# git push origin --tags
# no PR triggers
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: A
  condition: eq(variables['Build.SourceBranch'], 'master')
  jobs:
  - job: JA
    steps:
    - script: |
        echo "This is job Foo."
        echo $(System.PullRequest.TargetBranch)
      

#stage B runs if DetermineResult task set doThing variable n stage A
- stage: B
  dependsOn: A
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'master'))
  jobs:
  - job: JB
    steps:
    - bash: echo "Deployment to production"