jobs:
- deployment: Deploy
  dependsOn: Test
  displayName: Deploy
  environment: development
  continueOnError: false
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo 'Deploy'