# https://stackoverflow.com/questions/63733965/blazor-webassembly-azure-devops-build-pipeline-publish-artifacts

trigger:
- master

steps:
- pwsh: ls .

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: $(Build.SourcesDirectory)/stackoverflow/51-blazor-sample/BlazorSample

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)"'
    zipAfterPublish: false
    workingDirectory: $(Build.SourcesDirectory)/stackoverflow/51-blazor-sample/BlazorSample

- pwsh: ls '$(build.artifactstagingdirectory)'
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()