trigger:
  branches:
    include:
    - master
  paths:
    include:
    - stackoverflow/12-container-instance/*
    exclude:
    - '*'

# no PR triggers
pr: none

pool:
  vmImage: 'ubuntu-latest'

#https://stackoverflow.com/questions/61497425/azure-devops-azurecli-task-with-scriptpath-option-failed-to-authenticate-to-crea

steps:
- task: AzureCLI@2
  displayName: 'Run tests 1'
  inputs:
    azureSubscription: 'rg-the-code-manual'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '12-container-instance/create-container-instance.sh'

- task: AzureCLI@2
  displayName: 'Run tests 2'
  inputs:
    azureSubscription: 'rg-the-code-manual'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az container create -g TheCodeManual --name myapp2 --image $(Image) --registry-password $(RegistryPassword) --registry-user $(RegistryUser)'
