name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- pwsh: |
    echo some-text  > filename.txt
    cat filename.txt
    Write-Host ##vso[task.addattachment type=myattachmenttype;name=myattachmentname;]$(System.DefaultWorkingDirectory)/filename.txt
    Write-Host ##vso[task.uploadsummary]$(System.DefaultWorkingDirectory)/filename.txt

    Write-Host ##vso[task.addattachment type=myattachmenttype;name=myattachmentname;]filename.txt
    Write-Host ##vso[task.uploadsummary]filename.txt
