# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: 'Release'
  ${{  if e(variables['Test'], 'undefined') }}:
    value: 'Stage'
  ${{  if ne(variables['Test'], 'undefined') }}:
    value: 'Test'

steps:
- pwsh: |
    echo '$(Test)'
    echo '$(Test)'.Length
  displayName: 'Run a multi-line script'

- script: |
    echo $(Release)
  displayName: 'Run a multi-line script'
