trigger:
  branches:
    include:
      - master
  paths:
    include:
      - stackoverflow/05/*

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 3.x'
  inputs:
    version: 3.x