trigger: none

# no PR triggers
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: env | sort
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: rg-the-code-manual
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      az pipelines variable list --org https://dev.azure.com/thecodemanual/ --project $(System.TeamProjectId) --pipeline-id $(System.DefinitionId)