trigger:
- master

variables:
  BuildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

#https://stackoverflow.com/questions/61910176/how-to-deploy-a-webapp-from-a-folder-not-a-zip-in-azure-devops

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: true
    projects: |
      $(Build.SourcesDirectory)/stackoverflow/32-deploy-folder/SampleApp/SampleApp.csproj

- pwsh: ls $(Build.ArtifactStagingDirectory)