# https://stackoverflow.com/questions/58823004/how-can-i-use-if-else-in-variables-of-azure-devops-yaml-pipeline-with-variable-g

trigger: none
pr: none

stages:
- stage: One
  displayName: Build and restore
  variables:
  - group: PROD
  - name: env
    value:
      ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: a
      ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}: b
  jobs:
  - job: A
    steps:
    - script: | 
        echo '$(name)'
        echo '$(env)'

- stage: Two
  displayName: Build and restore
  variables:
  - group: PROD
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}
    - name: env
      value: a
  ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}
    - name: env
      value: b
  jobs:
  - job: A
    steps:
    - script: | 
        echo '$(name)'
        echo '$(env)'